spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hello_test?useUnicode=true
    username: root
    password: Root1234
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
  
server:  
  port: 8090  